#pragma once

using namespace Microsoft::Win32;
using namespace System;
using namespace System::Collections;
using namespace System::IO;
using namespace System::Runtime::Serialization::Json;
using namespace System::Windows::Forms;

namespace CreationKitAuditTool {

	class AchList
	{
	/**
	* Writes a file strings into a JSON-Encoded ACHLIST file.
	* @param manifest - The manifest to write to the ACHLIST file
	* @param fullname - The full name of the ACHLIST file to write
	* @param caller - The window to use for displaying Message Boxes.
	* @return true if the manifest was written to the ACHLIST file, false otherwise
	*/
	public: static bool WriteArrayToJsonFile(array<String^>^ manifest, String^ fullname, IWin32Window^ caller) {
		DataContractJsonSerializer^ deser = gcnew DataContractJsonSerializer(fullname->GetType());
		try {
			// Since the standard .NET Json DeSer has no format controls, in order
			// to write the ACHLIST file in the easily-readable form generated by
			// CK, we have to manually emit the open/close braces and then serialize
			// each string sequentially.
			System::IO::FileStream^ fh = nullptr;
			StreamWriter^ sw = nullptr;
			try {
				fh = File::Create(fullname);
				StreamWriter^ sw = gcnew StreamWriter(fh);
				sw->Write(L"[");
				sw->Flush();
				String^ prefix = L"\n\t";
				Collections::IEnumerator^ iter = manifest->GetEnumerator();
				while (iter->MoveNext()) {
					sw->Write(prefix);
					sw->Flush();
					deser->WriteObject(fh, cli::safe_cast<String^>(iter->Current));
					prefix = L",\n\t";
				}
				sw->Write(L"\n]");
				sw->Flush();
			}
			finally {
				if (nullptr != sw) {
					sw->Close();
				}
				else if (nullptr != fh) {
					fh->Close();
				}
			}
		}
		catch (Exception^ e) {
			MessageBox::Show(caller,
				L"Error creating " + fullname + L": " + e->Message,
				L"File Creation Error",
				MessageBoxButtons::OK,
				MessageBoxIcon::Error);
			return false;
		}
		return true;
	}
	/**
	* Reads the JSON-Enacoded ACHLIST file and returns its strings as an array of strings.
	* @param fullname - The full name of the ACHLIST file to read
	* @param caller - The window to use for displaying Message Boxes
	* @return An array containing the strings from the ACHLIST file, or nullptr
	* if the file could not be read
	*/
	public: static array<String^>^ ReadArrayFromJsonFile(String^ fullname, IWin32Window^ caller) {
		// Construct the serializer and read the data
		Array^ strings;
		array<String^>^ manifest = gcnew array<String^>(0);
		DataContractJsonSerializer^ deser = gcnew DataContractJsonSerializer(manifest->GetType());
		try {
			System::IO::FileStream^ fh = nullptr;
			try {
				fh = File::OpenRead(fullname);
				strings = cli::safe_cast<Array^>(deser->ReadObject(fh));
			}
			finally {
				if (nullptr != fh) {
					fh->Close();
				}
			}
		}
		catch (Exception^ e) {
			MessageBox::Show(caller,
				L"Error creating " + fullname + L": " + e->Message,
				L"File Creation Error",
				MessageBoxButtons::OK,
				MessageBoxIcon::Error);
			return nullptr;
		}
		manifest = gcnew array<String^>(strings->Length);
		for (int i = 0; i < strings->Length; i++) {
			manifest[i] = cli::safe_cast<String^>(strings->GetValue(i));
		}
		return manifest;
	}
	};

}

