#pragma once

using namespace Microsoft::Win32;
using namespace System;
using namespace System::Collections;
using namespace System::IO;
using namespace System::Runtime::Serialization::Json;
using namespace System::Windows::Forms;

namespace CreationKitAuditTool {

	class AchList
	{
	public: static System::Void WriteArrayToJsonFile(System::Array^ strings, String^ filename, IWin32Window^ caller) {
		DataContractJsonSerializer^ deser = gcnew DataContractJsonSerializer(filename->GetType());
		try {
			// Since the standard .NET Json DeSer has no format controls, in order
			// to write the ACHLIST file in the easily-readable form generated by
			// CK, we have to manually emit the open/close braces and then serialize
			// each string sequentially.
			System::IO::FileStream^ fh = nullptr;
			StreamWriter^ sw = nullptr;
			try {
				fh = File::Create(filename);
				StreamWriter^ sw = gcnew StreamWriter(fh);
				sw->Write(L"[");
				sw->Flush();
				String^ prefix = L"\n\t";
				IEnumerator^ iter = strings->GetEnumerator();
				while (iter->MoveNext()) {
					sw->Write(prefix);
					sw->Flush();
					deser->WriteObject(fh, cli::safe_cast<String^>(iter->Current));
					prefix = L",\n\t";
				}
				sw->Write(L"\n]");
				sw->Flush();
			}
			finally {
				if (nullptr != sw) {
					sw->Close();
				}
				else if (nullptr != fh) {
					fh->Close();
				}
			}
		}
		catch (Exception^ e) {
			MessageBox::Show(caller,
				L"Error creating " + filename + L": " + e->Message,
				L"File Creation Error",
				MessageBoxButtons::OK,
				MessageBoxIcon::Error);
		}
	}
	public: static System::Array^ ReadArrayFromJsonFile(String^ filename, IWin32Window^ caller) {
		// Some contortions to force the type data needed for the JSON Serializer
		ArrayList^ typedArray = gcnew ArrayList(0);
		System::Array^ strings = typedArray->ToArray(filename->GetType());

		// Construct the serializer and read the data
		DataContractJsonSerializer^ deser = gcnew DataContractJsonSerializer(strings->GetType());
		try {
			System::IO::FileStream^ fh = nullptr;
			try {
				fh = File::OpenRead(filename);
				strings = cli::safe_cast<System::Array^>(deser->ReadObject(fh));
			}
			finally {
				if (nullptr != fh) {
					fh->Close();
				}
			}
		}
		catch (Exception^ e) {
			MessageBox::Show(caller,
				L"Error creating " + filename + L": " + e->Message,
				L"File Creation Error",
				MessageBoxButtons::OK,
				MessageBoxIcon::Error);
		}
		return strings;
	}
	};

}

