#pragma once

using namespace Microsoft::Win32;
using namespace System;
using namespace System::Collections;
using namespace System::IO;
using namespace System::Runtime::Serialization::Json;
using namespace System::Windows::Forms;

namespace CreationKitAuditTool {

	class AchList
	{
	public: static bool WriteArrayToJsonFile(array<String^>^ strings, String^ filename, IWin32Window^ caller) {
		DataContractJsonSerializer^ deser = gcnew DataContractJsonSerializer(filename->GetType());
		try {
			// Since the standard .NET Json DeSer has no format controls, in order
			// to write the ACHLIST file in the easily-readable form generated by
			// CK, we have to manually emit the open/close braces and then serialize
			// each string sequentially.
			System::IO::FileStream^ fh = nullptr;
			StreamWriter^ sw = nullptr;
			try {
				fh = File::Create(filename);
				StreamWriter^ sw = gcnew StreamWriter(fh);
				sw->Write(L"[");
				sw->Flush();
				String^ prefix = L"\n\t";
				Collections::IEnumerator^ iter = strings->GetEnumerator();
				while (iter->MoveNext()) {
					sw->Write(prefix);
					sw->Flush();
					deser->WriteObject(fh, cli::safe_cast<String^>(iter->Current));
					prefix = L",\n\t";
				}
				sw->Write(L"\n]");
				sw->Flush();
			}
			finally {
				if (nullptr != sw) {
					sw->Close();
				}
				else if (nullptr != fh) {
					fh->Close();
				}
			}
		}
		catch (Exception^ e) {
			MessageBox::Show(caller,
				L"Error creating " + filename + L": " + e->Message,
				L"File Creation Error",
				MessageBoxButtons::OK,
				MessageBoxIcon::Error);
			return false;
		}
		return true;
	}
	public: static array<String^>^ ReadArrayFromJsonFile(String^ filename, IWin32Window^ caller) {
		// Construct the serializer and read the data
		Array^ manifest;
		array<String^>^ strings = gcnew array<String^>(0);
		DataContractJsonSerializer^ deser = gcnew DataContractJsonSerializer(strings->GetType());
		try {
			System::IO::FileStream^ fh = nullptr;
			try {
				fh = File::OpenRead(filename);
				manifest = cli::safe_cast<Array^>(deser->ReadObject(fh));
			}
			finally {
				if (nullptr != fh) {
					fh->Close();
				}
			}
		}
		catch (Exception^ e) {
			MessageBox::Show(caller,
				L"Error creating " + filename + L": " + e->Message,
				L"File Creation Error",
				MessageBoxButtons::OK,
				MessageBoxIcon::Error);
			return nullptr;
		}
		strings = gcnew array<String^>(manifest->Length);
		for (int i; i < manifest->Length; i++) {
			strings[i] = cli::safe_cast<String^>(manifest->GetValue(i));
		}
		return strings;
	}
	};

}

